// @generated by protobuf-ts 2.9.5
// @generated from protobuf file "TestUserSettings.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message TestUserSettings
 */
export interface TestUserSettings {
    /**
     * @generated from protobuf field: optional TestUserSettings.Versions versions = 1;
     */
    versions?: TestUserSettings_Versions;
    /**
     * @generated from protobuf field: optional TestUserSettings.ClientSettings settings = 2;
     */
    settings?: TestUserSettings_ClientSettings;
}
/**
 * @generated from protobuf message TestUserSettings.Versions
 */
export interface TestUserSettings_Versions {
    /**
     * @generated from protobuf field: uint32 client_version = 1;
     */
    clientVersion: number;
    /**
     * @generated from protobuf field: uint32 server_version = 2;
     */
    serverVersion: number;
    /**
     * @generated from protobuf field: uint32 data_version = 3;
     */
    dataVersion: number;
}
/**
 * @generated from protobuf message TestUserSettings.ClientMod
 */
export interface TestUserSettings_ClientMod {
    /**
     * @generated from protobuf field: bytes data = 1;
     */
    data: Uint8Array;
}
/**
 * @generated from protobuf message TestUserSettings.ClientSettings
 */
export interface TestUserSettings_ClientSettings {
    /**
     * @generated from protobuf field: TestUserSettings.ClientMod shared = 1;
     */
    shared?: TestUserSettings_ClientMod;
    /**
     * @generated from protobuf field: TestUserSettings.ClientMod vencord = 2;
     */
    vencord?: TestUserSettings_ClientMod;
}
// @generated message type with reflection information, may provide speed optimized methods
class TestUserSettings$Type extends MessageType<TestUserSettings> {
    constructor() {
        super("TestUserSettings", [
            { no: 1, name: "versions", kind: "message", T: () => TestUserSettings_Versions },
            { no: 2, name: "settings", kind: "message", T: () => TestUserSettings_ClientSettings }
        ]);
    }
    create(value?: PartialMessage<TestUserSettings>): TestUserSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<TestUserSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TestUserSettings): TestUserSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional TestUserSettings.Versions versions */ 1:
                    message.versions = TestUserSettings_Versions.internalBinaryRead(reader, reader.uint32(), options, message.versions);
                    break;
                case /* optional TestUserSettings.ClientSettings settings */ 2:
                    message.settings = TestUserSettings_ClientSettings.internalBinaryRead(reader, reader.uint32(), options, message.settings);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TestUserSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional TestUserSettings.Versions versions = 1; */
        if (message.versions)
            TestUserSettings_Versions.internalBinaryWrite(message.versions, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional TestUserSettings.ClientSettings settings = 2; */
        if (message.settings)
            TestUserSettings_ClientSettings.internalBinaryWrite(message.settings, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message TestUserSettings
 */
export const TestUserSettings = new TestUserSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TestUserSettings_Versions$Type extends MessageType<TestUserSettings_Versions> {
    constructor() {
        super("TestUserSettings.Versions", [
            { no: 1, name: "client_version", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "server_version", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "data_version", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<TestUserSettings_Versions>): TestUserSettings_Versions {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.clientVersion = 0;
        message.serverVersion = 0;
        message.dataVersion = 0;
        if (value !== undefined)
            reflectionMergePartial<TestUserSettings_Versions>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TestUserSettings_Versions): TestUserSettings_Versions {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 client_version */ 1:
                    message.clientVersion = reader.uint32();
                    break;
                case /* uint32 server_version */ 2:
                    message.serverVersion = reader.uint32();
                    break;
                case /* uint32 data_version */ 3:
                    message.dataVersion = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TestUserSettings_Versions, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 client_version = 1; */
        if (message.clientVersion !== 0)
            writer.tag(1, WireType.Varint).uint32(message.clientVersion);
        /* uint32 server_version = 2; */
        if (message.serverVersion !== 0)
            writer.tag(2, WireType.Varint).uint32(message.serverVersion);
        /* uint32 data_version = 3; */
        if (message.dataVersion !== 0)
            writer.tag(3, WireType.Varint).uint32(message.dataVersion);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message TestUserSettings.Versions
 */
export const TestUserSettings_Versions = new TestUserSettings_Versions$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TestUserSettings_ClientMod$Type extends MessageType<TestUserSettings_ClientMod> {
    constructor() {
        super("TestUserSettings.ClientMod", [
            { no: 1, name: "data", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<TestUserSettings_ClientMod>): TestUserSettings_ClientMod {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.data = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<TestUserSettings_ClientMod>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TestUserSettings_ClientMod): TestUserSettings_ClientMod {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes data */ 1:
                    message.data = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TestUserSettings_ClientMod, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes data = 1; */
        if (message.data.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.data);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message TestUserSettings.ClientMod
 */
export const TestUserSettings_ClientMod = new TestUserSettings_ClientMod$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TestUserSettings_ClientSettings$Type extends MessageType<TestUserSettings_ClientSettings> {
    constructor() {
        super("TestUserSettings.ClientSettings", [
            { no: 1, name: "shared", kind: "message", T: () => TestUserSettings_ClientMod },
            { no: 2, name: "vencord", kind: "message", T: () => TestUserSettings_ClientMod }
        ]);
    }
    create(value?: PartialMessage<TestUserSettings_ClientSettings>): TestUserSettings_ClientSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<TestUserSettings_ClientSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TestUserSettings_ClientSettings): TestUserSettings_ClientSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* TestUserSettings.ClientMod shared */ 1:
                    message.shared = TestUserSettings_ClientMod.internalBinaryRead(reader, reader.uint32(), options, message.shared);
                    break;
                case /* TestUserSettings.ClientMod vencord */ 2:
                    message.vencord = TestUserSettings_ClientMod.internalBinaryRead(reader, reader.uint32(), options, message.vencord);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TestUserSettings_ClientSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* TestUserSettings.ClientMod shared = 1; */
        if (message.shared)
            TestUserSettings_ClientMod.internalBinaryWrite(message.shared, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* TestUserSettings.ClientMod vencord = 2; */
        if (message.vencord)
            TestUserSettings_ClientMod.internalBinaryWrite(message.vencord, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message TestUserSettings.ClientSettings
 */
export const TestUserSettings_ClientSettings = new TestUserSettings_ClientSettings$Type();
